further setup

diff --git a/bin/check b/bin/check
--- a/bin/check
+++ b/bin/check
@@ -76,11 +76,11 @@ fi
 
 # for coffeescript
 
-coffeelint -f .coffeelint.json app/assets/javascripts/**/*.coffee
-if [ ! $? -eq 0 ]; then
-  echo 'coffeelint detected issues, commit aborted!'
-  exit 1
-fi
+# coffeelint -f .coffeelint.json app/assets/javascripts/**/*.coffee
+# if [ ! $? -eq 0 ]; then
+#   echo 'coffeelint detected issues, commit aborted!'
+#   exit 1
+# fi
 
 bundle exec brakeman -q -z --summary > /dev/null
 if [ ! $? -eq 0 ]; then
